# codemagic.yaml for Gigafy
workflows:
  ios-unsigned-gigafy:
    name: Gigafy iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2  # Optimized for 2026 build speeds
    environment:
      flutter: stable
      groups:
        - apple_credentials

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true

    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get

      - name: Install CocoaPods
        script: |
          # Navigate to ios directory
          cd ios
          
          # Check if the Podfile you manually created is actually present
          if [ -f "Podfile" ]; then
            echo "Podfile detected. Running pod install..."
            pod install
          else
            echo "Error: Podfile not found in /ios directory. Please ensure you pushed it to GitHub."
            exit 1
          fi

      - name: Build & Package Gigafy
        script: |
          # 1. Build the app bundle without signing
          flutter build ios --release --no-codesign

          # 2. Dynamically find the .app folder
          APP_NAME=$(find build/ios/iphoneos -name "*.app" | head -n 1)

          # 3. Create the IPA structure for distribution
          mkdir -p build/ios/iphoneos/Payload
          cp -r "$APP_NAME" build/ios/iphoneos/Payload/

          # 4. Zip the Payload into an .ipa file
          cd build/ios/iphoneos && zip -r Gigafy_Unsigned.ipa Payload

    artifacts:
      - build/ios/iphoneos/Gigafy_Unsigned.ipa

    publishing:
      email:
        recipients:
          - nicolejoycemanaloto8@gmail.com
          - jirogonzales777@gmail.com