# codemagic.yaml configuration
workflows:
  ios-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m2  # Recommended for 2026 builds
    max_build_duration: 60
    environment:
      groups:
        # You'll define these in Codemagic UI later (API keys, etc.)
        - apple_credentials
      vars:
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest # Uses Xcode 16.2+ as of early 2026
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true

    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build Flutter iOS
        # Using --no-codesign for initial setup test
        # Change to "flutter build ipa" once you set up code signing
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - nicolejoycemanaloto8@gmail.com
          - jirogonzales777@gmail.com