# 1. These lines are REQUIRED to tell the Podfile where Flutter is
target_path = File.expand_path('..', __FILE__)
source_path = File.join(target_path, 'Flutter', 'podhelper.rb')
require source_path

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 2. This command now works because of the 'require' at the top
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end